### PR TITLE
Multiplatform setup

### LINKED ISSUE #22: Better spongyCastle initialisation / decoupling
This is a follow-up for: https://github.com/walleth/kethereum/pull/21

There are now multiple of these blocks in kethereum:
```
    init {
        Security.insertProviderAt(org.spongycastle.jce.provider.BouncyCastleProvider(), 1)
    }
```

I would really like a cleaner way of initializing spongyCastle - and ideally a decoupling from sponygCastle from kethereum so it can also be used with bouncyCastle in a JVM context where the whole spongyCastle is not needed. 

One Idea: 
 * create a kethereum-android module that has to be included when using kethereum in combination with Android
 * inside this module there is a content-provider that initializes spongyCastle 

@mirceanis what do you think?

### LINKED ISSUE #31: rpc: replace moshi with kotlinx serializing
work towards #1 - still need to find a replacement for okhttp then - but as okio gets rewritten in kotlin currently - perhaps we will also see okhttp in pure kotlin

### LINKED ISSUE #61: Crypto API Multiplatform
Currently inside the `crypto_api` package we find the following piece of code: 

```kotlin
fun <T> loadClass(name: String): T = try {
    @Suppress("UNCHECKED_CAST")
    Class.forName("org.kethereum.crypto.impl.$name").newInstance() as T
} catch (e: ClassNotFoundException) {
    throw RuntimeException("There is not implementation found for $name - you need to either depend on crypto_impl_spongycastle or crypto_impl_bouncycastle")
}
```

While this works for JVM based project, I am not sure it will work on multiplatform projects too. 

I think, but I might be wrong, that we could replace the `loadClass` method with the [`actual/expected` mechanism](https://kotlinlang.org/docs/reference/platform-specific-declarations.html) allowing this library to be used inside multiplatform projects too.

### LINKED ISSUE #62: Multiplatform setup
Currently the project heavily depends on some methods that are available only on the JVM platform. 

For example, we can see the usage of `System.arrayCopy` method used in a lot of places, as well as `String.toCharArray` and other JVM-only methods. 

I think it would be great to set up the whole project to ne multiplatform ready, allowing us to delegate the implementation of such methods inside the proper JVM/JS/native modules. 

The problem is: I don't know which organization would be the best. Having all those small modules, how should be proceed into this? 

Working on this would make #61 easier

### PR DESCRIPTION
**Pull request by RiccardoM**
### Disclaimer
This is still WIP. I've opened it to let people know I'm working on this. Any feedback is appreciated. 

### Notes
First attempt to create a multiplatform project.

Currently revisited modules: 
- [x] abi
- [x] base58
- [x] bip32
- [x] bip39
- [x] bip39_wordlist_en
- [x] bip39_wordlist_es
- [x] bip39_wordlist_fr
- [x] bip39_wordlist_it
- [x] bip39_wordlist_ja
- [x] bip39_wordlist_ko
- [x] bip39_wordlist_zh-Hans
- [x] bip39_wordlist_zh-Hant
- [x] bip44
- [x] blockscout
- [x] contract_abi_types
- [x] crypto
- [x] crypto_api
- [x] crypto_impl_java_provider
- [x] crypto_impl_bouncycastle
- [x] crypto_impl_spongycastle
- [x] erc55
- [x] erc67
- [x] eip155
- [x] eip191
- [x] erc681
- [x] erc831
- [x] erc961
- [x] erc1328
- [x] Woretherscan
- [x] functions
- [x] hashes
- [x] keccak_shortcut
- [x] keystore
- [x] method_signatures
- [x] model
- [x] networks
- [x] ripemd160
- [x] rlp
- [x] rpc
- [x] test_data
- [x] uri_common
- [x] wallet

Missing modules to revisit:
- None

### Related issues
Closes #22
Closes #31
Closes #61
Closes #62

### CODE REVIEW

**Comment by RiccardoM** [comment]
@ligi The conversion is 99% done. We need to change the CI in order to execute the `gradle check` command to test everything automatically. Also there are some tests that are failing due to some errors. Can we look at them and try to fix them?

**Comment by ligi** [comment]
> We need to change the CI in order to execute the gradle check command to test everything automatically. 

this is as easy as adding a "check" to "stages" in here:
https://github.com/walleth/kethereum/blob/master/.ci/kontinuum.json

but what would it execute more than ./gradlew test is doing

> Can we look at them and try to fix them?

 am currently quite busy - so if I need to have a look it will take some time

> Note. In order to make this library 100% multiplatform, I had to copy/paste the Walleth/HEX and Wallet/SHA3 classes inside the project. To make them usable by this library, we need to convert them to multiplatform too.

is there really no other way? this would be quite ugly imho - perhaps a subproject? Really hope there is another way

**Comment by RiccardoM** [comment]
@ligi Understanding that you have not much time in order to maintain this project right now, my company decided to [fork a new project](https://github.com/Commercionetwork/borsellino) from here and start working on it. 

Unfortunately we need to have a multiplatform project that can be published properly on Bintray, and thus we had to revisit all the code structure and publishing pipeline. This, along with the fact that we will need to audit the codebase, has made us decide to start this new project, without forgetting and mentioning your work inside it. 

If you will you are super welcome to help up improve the project. From our part we will maintain the documentation and try implementing new features that are useful for us. 

That being said, I'm closing this PR right now being it outdated.

**Comment by ligi** [comment]
I have time to maintain this project and review pull requests. My mentioning having no time was regarding:

> Also there are some tests that are failing due to some errors. Can we look at them and try to fix them?

A bit sad this diverges now as I think this will be hard to converge again in the future.

**Comment by RdeWilde** [comment]
Why exactly is this issue closed? @RiccardoM 

Any other efforts for multiplatform?

**Pull request closed without merging**
